"""Add GPU memory and workload support fields

Revision ID: 001_add_gpu_memory_and_workload_fields
Revises: 
Create Date: 2025-04-03 11:02:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_add_gpu_memory_and_workload_fields'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new memory-related fields
    op.add_column('gpus', sa.Column('memory_gb', sa.Integer(), nullable=True))
    op.add_column('gpus', sa.Column('memory_type', sa.String(length=50), nullable=True))
    op.add_column('gpus', sa.Column('memory_bandwidth_tbps', sa.Float(), nullable=True))
    
    # Add FP4 support flag
    op.add_column('gpus', sa.Column('supports_fp4', sa.Boolean(), nullable=True))
    
    # Add interconnect and cooling fields
    op.add_column('gpus', sa.Column('interconnect_type', sa.String(length=50), nullable=True))
    op.add_column('gpus', sa.Column('cooling_requirement', sa.String(length=20), nullable=True))
    
    # Add supported workloads as JSON array
    op.add_column('gpus', sa.Column('supported_workloads', sa.JSON(), nullable=True))
    
    # Create indexes for performance
    op.create_index('idx_gpu_memory_gb', 'gpus', ['memory_gb'])
    op.create_index('idx_gpu_supports_fp4', 'gpus', ['supports_fp4'])
    op.create_index('idx_gpu_cooling_requirement', 'gpus', ['cooling_requirement'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_gpu_cooling_requirement', table_name='gpus')
    op.drop_index('idx_gpu_supports_fp4', table_name='gpus')
    op.drop_index('idx_gpu_memory_gb', table_name='gpus')
    
    # Drop columns
    op.drop_column('gpus', 'supported_workloads')
    op.drop_column('gpus', 'cooling_requirement')
    op.drop_column('gpus', 'interconnect_type')
    op.drop_column('gpus', 'supports_fp4')
    op.drop_column('gpus', 'memory_bandwidth_tbps')
    op.drop_column('gpus', 'memory_type')
    op.drop_column('gpus', 'memory_gb')
    
    # ### end Alembic commands ###
